server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true


#  security:
#    user:
#      name: username
#      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"

